services:
  db:
    image: postgres:16-alpine
    container_name: clover_db
    environment:
      POSTGRES_DB: cloverteste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clover_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=cloverteste;Username=postgres;Password=postgres
      - JWT_KEY=chave-1234567890-clover-test-chave-1234567890-clover-test
      - API_KEY_OPENWEATHER=74e9cc2b69f444bd1c0a35361def05eb
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clover_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
